#!/usr/bin/env bash
set -Eeuo pipefail

EXPECTED_STAGE5C_SHA256="${EXPECTED_STAGE5C_SHA256:-ffa8ecbf83a047f05cc1e4aeb3005b1fa8c09da651c273bb4a4d03a62a0dcacc}"

usage() {
  cat <<'EOF'
Usage:
  ./restore_sentinel_full.sh ARCHIVE.tar.gz [TARGET_SENTINEL_ROOT]

Default target:
  $HOME/robomaster/space/Sentinel_work

The script refuses to overwrite an existing SentinelWorkspace/workspace or
sentinelusd/Sentry_IsaacSim_Linux directory.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 1 || $# -gt 2 ]]; then
  usage >&2
  exit 64
fi

archive_path="$(realpath "$1")"
target_root="${2:-$HOME/robomaster/space/Sentinel_work}"
target_workspace="$target_root/SentinelWorkspace/workspace"
target_usd="$target_root/sentinelusd/Sentry_IsaacSim_Linux"
target_env="$target_root/migration_4090.env"

if [[ ! -f "$archive_path" ]]; then
  printf 'ERROR: archive not found: %s\n' "$archive_path" >&2
  exit 66
fi

for protected_target in "$target_workspace" "$target_usd" "$target_env"; do
  if [[ -e "$protected_target" ]]; then
    printf 'ERROR: destination already exists; nothing was overwritten: %s\n' "$protected_target" >&2
    exit 73
  fi
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXPECTED_STAGE5C_SHA256="$EXPECTED_STAGE5C_SHA256" \
  "$script_dir/verify_sentinel_archive.sh" "$archive_path"

temp_root="$(mktemp -d)"
cleanup() {
  rm -rf "$temp_root"
}
trap cleanup EXIT

tar -xzf "$archive_path" -C "$temp_root"
staged_root="$temp_root/SentinelMigration"

mkdir -p "$target_root/SentinelWorkspace" "$target_root/sentinelusd"
mv "$staged_root/SentinelWorkspace/workspace" "$target_workspace"
mv "$staged_root/sentinelusd/Sentry_IsaacSim_Linux" "$target_usd"

metadata_target="$target_root/migration_metadata"
if [[ -e "$metadata_target" ]]; then
  metadata_target="$target_root/migration_metadata_$(date -u +%Y%m%dT%H%M%SZ)"
fi
mv "$staged_root/metadata" "$metadata_target"

actual_stage5c_sha256="$(sha256sum "$target_usd/output/Sentry_stage5c_joint_drives.usda" | awk '{print $1}')"
if [[ "$actual_stage5c_sha256" != "$EXPECTED_STAGE5C_SHA256" ]]; then
  printf 'ERROR: post-restore Stage5C verification failed.\n' >&2
  exit 65
fi

isaac_root="$HOME/issac-sim/isaac-sim"
if [[ ! -d "$isaac_root" && -d "$HOME/isaac-sim/isaac-sim" ]]; then
  printf 'WARNING: found isaac-sim spelling, but the Sentinel baseline expects issac-sim.\n' >&2
  isaac_root="$HOME/isaac-sim/isaac-sim"
fi

cat > "$target_env" <<EOF
# Generated by restore_sentinel_full.sh
export SENTINEL_ROOT="$target_root"
export SENTRY_WORKSPACE="$target_workspace"
export SENTRY_USD_PROJECT="$target_usd"
export SENTRY_USD_PATH="$target_usd/output/Sentry_stage5d_swerve.usda"
export ISAAC_SIM_ROOT="$isaac_root"
export ROS_DISTRO="jazzy"
export ROS_DOMAIN_ID="0"
export RMW_IMPLEMENTATION="rmw_fastrtps_cpp"
EOF
chmod 600 "$target_env"

printf '\nRestore completed.\n'
printf 'Workspace:   %s\n' "$target_workspace"
printf 'USD project: %s\n' "$target_usd"
printf 'Metadata:    %s\n' "$metadata_target"
printf 'Environment: %s\n' "$target_env"
printf 'Stage5C SHA256: %s\n' "$actual_stage5c_sha256"
printf '\nNext: run check_4090_host.sh before building or modifying code.\n'
