#!/usr/bin/env bash
set -Eeuo pipefail

EXPECTED_STAGE5C_SHA256="${EXPECTED_STAGE5C_SHA256:-ffa8ecbf83a047f05cc1e4aeb3005b1fa8c09da651c273bb4a4d03a62a0dcacc}"

usage() {
  cat <<'EOF'
Usage:
  ./restore_sentinel_5090.sh ARCHIVE.tar.gz [TARGET_SENTINEL_ROOT]

Default target:
  $HOME/RoboMaster/Sentinel

The script refuses to overwrite an existing SentinelWorkspace/workspace or
sentinelusd/Sentry_IsaacSim_Linux directory.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 1 || $# -gt 2 ]]; then
  usage >&2
  exit 64
fi

archive_path="$(realpath "$1")"
target_root="${2:-$HOME/RoboMaster/Sentinel}"
target_workspace="$target_root/SentinelWorkspace/workspace"
target_usd="$target_root/sentinelusd/Sentry_IsaacSim_Linux"
target_env="$target_root/migration_5090.env"

if [[ ! -f "$archive_path" ]]; then
  printf 'ERROR: archive not found: %s\n' "$archive_path" >&2
  exit 66
fi

if [[ -e "$target_workspace" ]]; then
  printf 'ERROR: destination already exists; nothing was overwritten: %s\n' "$target_workspace" >&2
  exit 73
fi

if [[ -e "$target_usd" ]]; then
  printf 'ERROR: destination already exists; nothing was overwritten: %s\n' "$target_usd" >&2
  exit 73
fi

if [[ -e "$target_env" ]]; then
  printf 'ERROR: environment file already exists; nothing was overwritten: %s\n' "$target_env" >&2
  exit 73
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXPECTED_STAGE5C_SHA256="$EXPECTED_STAGE5C_SHA256" \
  "$script_dir/verify_sentinel_archive.sh" "$archive_path"

temp_root="$(mktemp -d)"
cleanup() {
  rm -rf "$temp_root"
}
trap cleanup EXIT

tar -xzf "$archive_path" -C "$temp_root"
staged_root="$temp_root/SentinelMigration"

mkdir -p "$target_root/SentinelWorkspace" "$target_root/sentinelusd"
mv "$staged_root/SentinelWorkspace/workspace" "$target_workspace"
mv "$staged_root/sentinelusd/Sentry_IsaacSim_Linux" "$target_usd"

metadata_target="$target_root/migration_metadata"
if [[ -e "$metadata_target" ]]; then
  metadata_target="$target_root/migration_metadata_$(date -u +%Y%m%dT%H%M%SZ)"
fi
mv "$staged_root/metadata" "$metadata_target"

actual_stage5c_sha256="$(sha256sum "$target_usd/output/Sentry_stage5c_joint_drives.usda" | awk '{print $1}')"
if [[ "$actual_stage5c_sha256" != "$EXPECTED_STAGE5C_SHA256" ]]; then
  printf 'ERROR: post-restore Stage5C verification failed.\n' >&2
  exit 65
fi

cat > "$target_env" <<EOF
# Generated by restore_sentinel_5090.sh
export SENTRY_WORKSPACE="$target_workspace"
export SENTRY_USD_PROJECT="$target_usd"
export SENTRY_USD_PATH="$target_usd/output/Sentry_stage5d_swerve.usda"
export ISAAC_SIM_ROOT="$HOME/issac-sim/isaac-sim"
export ROS_DISTRO="jazzy"
export ROS_DOMAIN_ID="0"
export RMW_IMPLEMENTATION="rmw_fastrtps_cpp"
EOF
chmod 600 "$target_env"

printf '\nRestore completed.\n'
printf 'Workspace:   %s\n' "$target_workspace"
printf 'USD project: %s\n' "$target_usd"
printf 'Metadata:    %s\n' "$metadata_target"
printf 'Environment: %s\n' "$target_env"
printf 'Stage5C SHA256: %s\n' "$actual_stage5c_sha256"
printf '\nNext: install Isaac Sim 6.0.1 separately under ~/issac-sim/isaac-sim, then run:\n'
printf '  source %q\n' "$target_env"
printf '  cd %q\n' "$target_workspace"
printf '  source tools/integration/sentinel_env.sh\n'
printf '  ./tools/ubuntu/doctor.sh\n'
