std_msgs/Header header
uint8 ego_team
uint8 ego_type
float32 elapsed_s
float32 remaining_s
sentinel_interfaces/BattleEntity ego
sentinel_interfaces/BattleEntity[] allies
sentinel_interfaces/BattleEntity[] enemies

float32 own_base_hp
float32 own_base_max_hp
float32 own_outpost_hp
float32 own_outpost_max_hp
float32 enemy_base_hp
float32 enemy_base_max_hp
float32 enemy_outpost_hp
float32 enemy_outpost_max_hp

float32 own_coin_left
float32 own_coin_total
float32 enemy_coin_total
float32[6] team_prior
